Models/Road_Craft.cs
using AirLine.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AirLine.Models
{
    public class Road_Craft:Entity<int>
    {
        //route_id /craft_id/departure/ price/ num_of_passenger/ arrival
        //duration derived

        public int RouteId { get; set; }
        public int AirCraftId { get; set; }

        [DataType(DataType.Time)]
        public DateTime DepatureTime { get; set; }

        [DataType(DataType.Time)]
        public DateTime ArrivalTime { get; set; }

        [Column(TypeName ="money")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        public int NumPassenger { get; set; }

        ////not must navigational property
        //public Road Road { get; set; }
        //public AirCraft AirCraft { get; set; }

    }
}

Controllers/Road_CraftController.cs
using AirLine.Models;
using AirLine.MyDBContext;
using AirLine.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AirLine.Controllers
{
    public class Road_CraftController : Controller
    {
        private readonly DBContext _dBContext;

        public Road_CraftController(DBContext dBContext)
        {
            _dBContext = dBContext;
        }
        // GET: Road_CraftController1
        public ActionResult Index()
        {
           // var roadCrafts1 = _dBContext.Road_Crafts
           //.Include(rc => rc.RouteId )
           //.Include(rc => rc.AirCraftId)
           //.ToList();

            var roadCrafts = _dBContext.Road_Crafts.ToList();
            var RoCrafModel = new List<Road_CraftModel>();
            foreach (var road in roadCrafts)
            {



                var viewModel = new Road_CraftModel()
                {

                    RouteId = road.RouteId,
                    AirCraftId = road.AirCraftId,
                    DepatureTime = road.DepatureTime,
                    ArrivalTime = road.ArrivalTime,
                    NumPassenger = road.NumPassenger,
                    Price = road.Price,
                    CreatedDate = road.CreatedDate,
                    UpdatedDate = road.UpdatedDate,
                    IsDeleted = road.IsDeleted,
                    IsVisable = road.IsVisable,
                };
                RoCrafModel.Add(viewModel);

            }

            return View(RoCrafModel);

        }

        // GET: Road_CraftController1/Details/5
        public ActionResult Details(int id)
        {
            var RoCraftDE = _dBContext.Road_Crafts.Where(r => r.Id == id).FirstOrDefault();

            return View(RoCraftDE);
        }

        // GET: Road_CraftController1/Create
        public ActionResult Create()
        {
            Road_CraftModel CraftModel = new Road_CraftModel();
            var airline = _dBContext.AirCrafts.ToList();
            var roads = _dBContext.Roads.ToList();
            CraftModel.AirCRS= airline;
            CraftModel.RDs = roads;
            return View(CraftModel);
        }

        // POST: Road_CraftController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Road_CraftModel road_CraftModel)
        {
            try
            {
                Road_Craft craftR = new Road_Craft()
                {
                   RouteId= road_CraftModel.RouteId,
                   AirCraftId= road_CraftModel.AirCraftId,
                    DepatureTime = road_CraftModel.DepatureTime,
                    ArrivalTime = road_CraftModel.ArrivalTime,
                    NumPassenger = road_CraftModel.NumPassenger,
                    Price = road_CraftModel.Price,
                    CreatedDate = DateTime.Now,
                    UpdatedDate = DateTime.Now,
                    IsDeleted = false,
                    IsVisable = true,


                };
                craftR.IsDeleted = false;
                craftR.IsVisable = true;
                _dBContext.Add(craftR);

                _dBContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Road_CraftController1/Edit/5
        public ActionResult Edit(int id)
        {
            //Road_CraftModel TranModel = new Road_CraftModel();
            var craft = _dBContext.AirCrafts.ToList();
            //TransactionModel TranModel = new TransactionModel();
            var road = _dBContext.Roads.ToList();

            var CraftE = _dBContext.Road_Crafts.Where(r => r.Id == id).FirstOrDefault();
            var viewModel = new Road_CraftModel
            {
                RouteId= CraftE.RouteId,
                AirCraftId= CraftE.AirCraftId,
                DepatureTime = CraftE.DepatureTime,
                ArrivalTime = CraftE.ArrivalTime,
                NumPassenger = CraftE.NumPassenger,
                Price = CraftE.Price,

                IsDeleted = CraftE.IsDeleted,
                IsVisable = CraftE.IsVisable,
                CreatedDate = CraftE.CreatedDate,
                UpdatedDate = CraftE.UpdatedDate,
            };
            viewModel.AirCRS = craft;
            viewModel.RDs = road;
            return View(viewModel);
        }

        // POST: Road_CraftController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Road_CraftModel road_CraftModel)
        {
            try
            {

                var originalRoad = _dBContext.Road_Crafts.Where(r => r.Id == road_CraftModel.RouteId).FirstOrDefault();


                originalRoad.RouteId = road_CraftModel.RouteId;
                originalRoad.AirCraftId = road_CraftModel.AirCraftId;
                originalRoad.DepatureTime = road_CraftModel.DepatureTime;
                originalRoad.ArrivalTime = road_CraftModel.ArrivalTime;
                originalRoad.NumPassenger = road_CraftModel.NumPassenger;
                originalRoad.Price = road_CraftModel.Price;

                originalRoad.IsVisable = road_CraftModel.IsVisable;
                originalRoad.IsDeleted = road_CraftModel.IsDeleted;
                originalRoad.CreatedDate = road_CraftModel.CreatedDate;
                originalRoad.UpdatedDate = road_CraftModel.UpdatedDate;



                _dBContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Road_CraftController1/Delete/5
        public ActionResult Delete(int id)
        {
            var ROCD = _dBContext.Road_Crafts.Where(r => r.Id == id).FirstOrDefault();
            return View(ROCD);
        }

        // POST: Road_CraftController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Road_Craft road_Craft)
        {
            try
            {

                var RCDelete = _dBContext.Road_Crafts.Where(r => r.Id == road_Craft.Id).FirstOrDefault();
                _dBContext.Road_Crafts.Remove(RCDelete);

                _dBContext.SaveChanges();
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Road_Craft/Create.cshtml
@model AirLine.ViewModel.Road_CraftModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Road_Craft</h1>

<hr />
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Create Road_Craft</h5>

        <!-- No Labels Form -->
        <form class="row g-3" asp-action="Create" asp-controller="Road_Craft">
            <div class="col-md-6">
                <label>AirCraft Name</label>
                <select asp-for="AirCraftId" class="form-control" asp-items="@(new SelectList(Model.AirCRS,  "Id" ,"Model" ))"></select>

            </div>
            <div class="col-md-6">
                <label>Road Name</label>
                <select asp-for="RouteId" class="form-control" asp-items="@(new SelectList(Model.RDs,"Id" ,"Distination" ))"></select>

            </div>
           
            <div class="col-md-6">
                <label>DepatureTime</label>
                <input asp-for="DepatureTime" class="form-control" placeholder="DepatureTime">
            </div>
            <div class="col-md-6">
                <label>ArrivalTime</label>
                <input asp-for="ArrivalTime" class="form-control" placeholder="ArrivalTime">
            </div>
            <div class="col-md-6">
                <label >NumPassenger</label>
                <input asp-for="NumPassenger" class="form-control" placeholder="NumPassenger">
            </div>
            <div class="col-md-6">
                <label >Price</label>
                <input asp-for="Price" class="form-control" placeholder="Price">
            </div>

           
           
            @* <div class="col-md-4">
            <select asp-for="Classification" id="inputState" class="form-select" placeholder="Classification">
            <option>domestic</option>
            <option>international route</option>
            </select>
            </div>*@

            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form><!-- End No Labels Form -->

    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Road_Craft/Delete.cshtml
@model AirLine.Models.Road_Craft

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Road_Craft</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RouteId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RouteId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirCraftId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirCraftId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepatureTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepatureTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumPassenger)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumPassenger)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVisable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVisable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Road_Craft/Details.cshtml
@model AirLine.Models.Road_Craft

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Road_Craft</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RouteId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RouteId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirCraftId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirCraftId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepatureTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepatureTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumPassenger)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumPassenger)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVisable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVisable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Road_Craft/Edit.cshtml
@model AirLine.ViewModel.Road_CraftModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Road_CraftModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label>Road Name</label>
                <select asp-for="RouteId" class="form-control" asp-items="@(new SelectList(Model.RDs,"Id" ,"Distination" ))"></select>

            </div>
            <div class="form-group">
                <label>AirCraft Name</label>
                <select asp-for="AirCraftId" class="form-control" asp-items="@(new SelectList(Model.AirCRS,  "Id" ,"Model" ))"></select>

            </div>
            <div class="form-group">
                <label asp-for="DepatureTime" class="control-label"></label>
                <input asp-for="DepatureTime" class="form-control" />
                <span asp-validation-for="DepatureTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalTime" class="control-label"></label>
                <input asp-for="ArrivalTime" class="form-control" />
                <span asp-validation-for="ArrivalTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumPassenger" class="control-label"></label>
                <input asp-for="NumPassenger" class="form-control" />
                <span asp-validation-for="NumPassenger" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVisable" /> @Html.DisplayNameFor(model => model.IsVisable)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Road_Craft/Index.cshtml
@model IEnumerable<AirLine.ViewModel.Road_CraftModel>

@{
	ViewData["Title"] = "Index";
}

<h1>Road_Craft</h1>



<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Bootstrap CRUD Data Table for Database with Modal Form</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
	<style>
		body {
			color: #566787;
			background: #f5f5f5;
			font-family: 'Varela Round', sans-serif;
			font-size: 14px;
		}

		.table-responsive {
			margin: 30px 0;
		}

		.table-wrapper {
			background: #fff;
			padding: 20px 25px;
			border-radius: 3px;
			min-width: 1000px;
			box-shadow: 0 1px 1px rgba(0,0,0,.05);
		}

		.table-title {
			padding-bottom: 15px;
			background: #435d7d;
			color: #fff;
			padding: 16px 30px;
			min-width: 100%;
			margin: -20px -25px 10px;
			border-radius: 3px 3px 0 0;
		}

			.table-title h2 {
				margin: 5px 0 0;
				font-size: 24px;
			}

			.table-title .btn-group {
				float: right;
			}

			.table-title .btn {
				color: #fff;
				float: right;
				font-size: 13px;
				border: none;
				min-width: 50px;
				border-radius: 2px;
				border: none;
				outline: none !important;
				margin-left: 10px;
			}

				.table-title .btn i {
					float: left;
					font-size: 21px;
					margin-right: 5px;
				}

				.table-title .btn span {
					float: left;
					margin-top: 2px;
				}

		table.table tr th, table.table tr td {
			border-color: #e9e9e9;
			padding: 12px 15px;
			vertical-align: middle;
		}

			table.table tr th:first-child {
				width: 60px;
			}

			table.table tr th:last-child {
				width: 100px;
			}

		table.table-striped tbody tr:nth-of-type(odd) {
			background-color: #fcfcfc;
		}

		table.table-striped.table-hover tbody tr:hover {
			background: #f5f5f5;
		}

		table.table th i {
			font-size: 13px;
			margin: 0 5px;
			cursor: pointer;
		}

		table.table td:last-child i {
			opacity: 0.9;
			font-size: 22px;
			margin: 0 5px;
		}

		table.table td a {
			font-weight: bold;
			color: #566787;
			display: inline-block;
			text-decoration: none;
			outline: none !important;
		}

			table.table td a:hover {
				color: #2196F3;
			}

			table.table td a.edit {
				color: #FFC107;
				font-size:25px;
			}

			table.table td a.details {
				color: color: #2196F3;
				font-size: 25px;
			}

			table.table td a.delete {
				color: #F44336;
			}

		table.table td i {
			font-size: 19px;
		}

		table.table .avatar {
			border-radius: 50%;
			vertical-align: middle;
			margin-right: 10px;
		}

		.pagination {
			float: right;
			margin: 0 0 5px;
		}

			.pagination li a {
				border: none;
				font-size: 13px;
				min-width: 30px;
				min-height: 30px;
				color: #999;
				margin: 0 2px;
				line-height: 30px;
				border-radius: 2px !important;
				text-align: center;
				padding: 0 6px;
			}

				.pagination li a:hover {
					color: #666;
				}

			.pagination li.active a, .pagination li.active a.page-link {
				background: #03A9F4;
			}

				.pagination li.active a:hover {
					background: #0397d6;
				}

			.pagination li.disabled i {
				color: #ccc;
			}

			.pagination li i {
				font-size: 16px;
				padding-top: 6px
			}

		.hint-text {
			float: left;
			margin-top: 10px;
			font-size: 13px;
		}
		/* Custom checkbox */
		.custom-checkbox {
			position: relative;
		}

			.custom-checkbox input[type="checkbox"] {
				opacity: 0;
				position: absolute;
				margin: 5px 0 0 3px;
				z-index: 9;
			}

			.custom-checkbox label:before {
				width: 18px;
				height: 18px;
			}

			.custom-checkbox label:before {
				content: '';
				margin-right: 10px;
				display: inline-block;
				vertical-align: text-top;
				background: white;
				border: 1px solid #bbb;
				border-radius: 2px;
				box-sizing: border-box;
				z-index: 2;
			}

			.custom-checkbox input[type="checkbox"]:checked + label:after {
				content: '';
				position: absolute;
				left: 6px;
				top: 3px;
				width: 6px;
				height: 11px;
				border: solid #000;
				border-width: 0 3px 3px 0;
				transform: inherit;
				z-index: 3;
				transform: rotateZ(45deg);
			}

			.custom-checkbox input[type="checkbox"]:checked + label:before {
				border-color: #03A9F4;
				background: #03A9F4;
			}

			.custom-checkbox input[type="checkbox"]:checked + label:after {
				border-color: #fff;
			}

			.custom-checkbox input[type="checkbox"]:disabled + label:before {
				color: #b8b8b8;
				cursor: auto;
				box-shadow: none;
				background: #ddd;
			}
		/* Modal styles */
		.modal .modal-dialog {
			max-width: 400px;
		}

		.modal .modal-header, .modal .modal-body, .modal .modal-footer {
			padding: 20px 30px;
		}

		.modal .modal-content {
			border-radius: 3px;
			font-size: 14px;
		}

		.modal .modal-footer {
			background: #ecf0f1;
			border-radius: 0 0 3px 3px;
		}

		.modal .modal-title {
			display: inline-block;
		}

		.modal .form-control {
			border-radius: 2px;
			box-shadow: none;
			border-color: #dddddd;
		}

		.modal textarea.form-control {
			resize: vertical;
		}

		.modal .btn {
			border-radius: 2px;
			min-width: 100px;
		}

		.modal form label {
			font-weight: normal;
		}
	</style>
	<script>
		$(document).ready(function () {
			// Activate tooltip
			$('[data-toggle="tooltip"]').tooltip();

			// Select/Deselect checkboxes
			var checkbox = $('table tbody input[type="checkbox"]');
			$("#selectAll").click(function () {
				if (this.checked) {
					checkbox.each(function () {
						this.checked = true;
					});
				} else {
					checkbox.each(function () {
						this.checked = false;
					});
				}
			});
			checkbox.click(function () {
				if (!this.checked) {
					$("#selectAll").prop("checked", false);
				}
			});
		});
	</script>
</head>
<body>
	@if (Model != null)
	{
			<div class="container-l">
				<div class="table-responsive">
					<div class="table-wrapper">
						<div class="table-title">
							<div class="row">
								<div class="col-sm-6">
								<h2>Manage <b>Road_Craft</b></h2>
								</div>
								<div class="col-sm-6">

								<a asp-action="Create" class="btn btn-success"><i class="material-icons">&#xE147;</i> <span>Add New Road_Craft</span></a>



								</div>
							</div>
						</div>
						<table class="table table-striped table-hover">
							<thead>
								<tr>

									<th>
									@Html.DisplayNameFor(model => model.RouteId)
									</th>
									<th>
									@Html.DisplayNameFor(model => model.AirCraftId)
									</th>
									<th>
									@Html.DisplayNameFor(model => model.DepatureTime)
									</th>
									<th>
									@Html.DisplayNameFor(model => model.ArrivalTime)
									</th>
									<th>
									@Html.DisplayNameFor(model => model.NumPassenger)
									</th>
									<th>
									@Html.DisplayNameFor(model => model.Price)
									</th>
									

									<th>
									@Html.DisplayNameFor(model => model.CreatedDate)
									</th>


								</tr>
							</thead>
							<tbody>
								<tr>

								@foreach (var item in Model)
								{
										<tr>



											<td>
											@Html.DisplayFor(modelItem => item.RouteId)
											</td>
											<td>
											@Html.DisplayFor(modelItem => item.AirCraftId)
											</td>
											<td>
											@Html.DisplayFor(modelItem => item.DepatureTime)
											</td>
											<td>
											@Html.DisplayFor(modelItem => item.ArrivalTime)
											</td>
											<td>
											@Html.DisplayFor(modelItem => item.NumPassenger)
											</td>

											<td>
											@Html.DisplayFor(modelItem => item.Price)
											</td>
											

											<td>
											@Html.DisplayFor(modelItem => item.CreatedDate)
											</td>


											<td>
										<a class="edit" asp-action="Edit" ><i class="material-icons" title="Edit" style="margin-top=30px">&#xE254;</i></a>
										<a class="delete" asp-action="Delete" ><i class="material-icons" title="Delete" style="margin-top=30px">&#xE872;</i></a>
										<a class="details" asp-action="Details" ><img class="material-icons" src="~/NiceAdmin/assets/img/icons8-info-48.png" style="width:25px;height=20px ;margin-bottom=30px" /></a>

											</td>
										</tr>
								}



								</tr>

							</tbody>
						</table>

					</div>
				</div>
			</div>
	}
	else
	{
			<h1>No Data Available</h1>
	}
	
</body>
</html>