Models/Road.cs
using AirLine.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AirLine.Models
{
    public class Road:Entity<int>
    {
        // rout_id/ origin/distination /distance/ classification

       
        public string Origin { get; set; }
        public string Distination { get; set; }
        public double Distance { get; set; }

        public string  Classification { get; set; }

        public ICollection<Road_Craft> Road_Crafts { get; set; } 
    }
}

Controllers/RoadController.cs
using AirLine.Models;
using AirLine.MyDBContext;
using AirLine.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;

namespace AirLine.Controllers
{
    public class RoadController : Controller
    {
        private readonly DBContext _dBContext;

        public RoadController(DBContext dBContext)
        {
			_dBContext= dBContext;


		}
        // GET: RoadController
        public ActionResult Index()
        {
			var roads = _dBContext.Roads.ToList();

			var roadmodel = new List<RoadModel>();
			foreach (var road in roads)
			{
				var viewModel = new RoadModel()
				{
					Id = road.Id,
					Origin = road.Origin,
					Distance = road.Distance,
					Distination = road.Distination,
					Classification = road.Classification,
					CreatedDate = road.CreatedDate,
					UpdatedDate = road.UpdatedDate,
					IsDeleted = road.IsDeleted,
					IsVisable = road.IsVisable,
				};
				roadmodel.Add(viewModel);
			}
			return View(roadmodel);

        }

        // GET: RoadController/Details/5
        public ActionResult Details(int id)
        {
			var roadDE = _dBContext.Roads.Where(r => r.Id == id).FirstOrDefault();

			return View(roadDE);
        }

        // GET: RoadController/Create
        public ActionResult Create()
        { 
             var viewModel = new RoadModel();

			return View(viewModel);
        }

        // POST: RoadController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoadModel roadModel)
        {
            try
            {
                Road road1=new Road() { 
                    Id= roadModel.Id,
                    Origin= roadModel.Origin,
                    Distance= roadModel.Distance,
                    Distination= roadModel.Distination,
                    Classification= roadModel.Classification,
                    CreatedDate=DateTime.Now,
                    UpdatedDate=DateTime.Now,
                    IsDeleted=false,
                    IsVisable=true,


                };
                _dBContext.Add(road1);
                //_dBContext.Roads.Add(road1);
                _dBContext.SaveChanges();

				return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RoadController/Edit/5
        public ActionResult Edit(int id)
        {
           var roadE= _dBContext.Roads.Where(r => r.Id == id).FirstOrDefault();
			var viewModel = new RoadModel
			{
				Id = roadE.Id,
				Origin = roadE.Origin,
				Distination = roadE.Distination,
				Distance = roadE.Distance,
				Classification = roadE.Classification,
                IsVisable= roadE.IsVisable,
                IsDeleted = roadE.IsDeleted,
                CreatedDate = DateTime.Now,
                UpdatedDate = DateTime.Now,
			};

			return View(viewModel);
			
		}
       
		// POST: RoadController/Edit/5
		[HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoadModel roadModel)
        {
            try
            {

				var originalRoad = _dBContext.Roads.Where(r => r.Id == roadModel.Id).FirstOrDefault();

				originalRoad.Id= roadModel.Id;
				originalRoad.Origin = roadModel.Origin;
				originalRoad.Distination = roadModel.Distination;
				originalRoad.Distance = roadModel.Distance;
				originalRoad.Classification = roadModel.Classification;
                originalRoad.IsVisable = roadModel.IsVisable;
                originalRoad.IsDeleted = roadModel.IsDeleted;
                originalRoad.CreatedDate = roadModel.CreatedDate;
                originalRoad.UpdatedDate = roadModel.UpdatedDate;


                
                _dBContext.SaveChanges();
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }

        // GET: RoadController/Delete/5
        public ActionResult Delete(int id)
        {
			var roadD = _dBContext.Roads.Where(r => r.Id == id).FirstOrDefault();
			
			return View(roadD);
			
        }

        // POST: RoadController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Road road)
        {
            try
            {
				var RoadDelete = _dBContext.Roads.Where(r => r.Id == road.Id).FirstOrDefault();
				_dBContext.Roads.Remove(RoadDelete);
			
				_dBContext.SaveChanges();
				return RedirectToAction(nameof(Index));
			
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Road/Create.cshtml
@model AirLine.ViewModel.RoadModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Road</h1>


<hr />

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Create Road</h5>

        <!-- No Labels Form -->
        <form class="row g-3" asp-action="Create" asp-controller="Road">
            <div class="col-md-6">
                <label>ID</label>
                <input asp-for="Id" class="form-control" placeholder="ID">
            </div>
            <div class="col-md-6">
                <label>Origin</label>
                <input asp-for="Origin" class="form-control" placeholder="Origin">
            </div>
            <div class="col-md-6">
                <label>Distination</label>
                <input asp-for="Distination" class="form-control" placeholder="Distination">
            </div>
            <div class="col-md-6">
                <label>Distance</label>
                <input asp-for="Distance" class="form-control" placeholder="Distance">
            </div>

            
            <div class="col-md-4">
                <label>Classification</label>
                <select asp-for="Classification" id="inputState" class="form-select" placeholder="Classification">
                    <option  >domestic</option>
                    <option>international route</option>
                </select>
            </div>
           
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
               </div>
        </form><!-- End No Labels Form -->

    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Road/Delete.cshtml
@model AirLine.Models.Road

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Road</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
  
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Distination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Distination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Distance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Distance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Classification)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Classification)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVisable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVisable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-primary">Back to List</a>
    </form>
</div>

Views/Road/Details.cshtml
@model AirLine.Models.Road

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Road</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Distination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Distination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Distance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Distance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Classification)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Classification)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVisable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVisable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Road/Edit.cshtml
@model AirLine.ViewModel.RoadModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Road</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Origin" class="control-label"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Distination" class="control-label"></label>
                <input asp-for="Distination" class="form-control" />
                <span asp-validation-for="Distination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Distance" class="control-label"></label>
                <input asp-for="Distance" class="form-control" />
                <span asp-validation-for="Distance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Classification" class="control-label"></label>
                <input asp-for="Classification" class="form-control" />
                <span asp-validation-for="Classification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVisable" /> @Html.DisplayNameFor(model => model.IsVisable)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top=12px;">
                <input type="submit" value="Save" class="btn btn-primary " />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Road/Index.cshtml
@model IEnumerable<AirLine.ViewModel.RoadModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Data Of Road</h1>


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Bootstrap CRUD Data Table for Database with Modal Form</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
	<style>
		body {
			color: #566787;
			background: #f5f5f5;
			font-family: 'Varela Round', sans-serif;
			font-size: 14px;
		}

		.table-responsive {
			margin: 30px 0;
		}

		.table-wrapper {
			background: #fff;
			padding: 20px 25px;
			border-radius: 3px;
			min-width: 1000px;
			box-shadow: 0 1px 1px rgba(0,0,0,.05);
		}

		.table-title {
			padding-bottom: 15px;
			background: #435d7d;
			color: #fff;
			padding: 16px 30px;
			min-width: 100%;
			margin: -20px -25px 10px;
			border-radius: 3px 3px 0 0;
		}

			.table-title h2 {
				margin: 5px 0 0;
				font-size: 24px;
			}

			.table-title .btn-group {
				float: right;
			}

			.table-title .btn {
				color: #fff;
				float: right;
				font-size: 13px;
				border: none;
				min-width: 50px;
				border-radius: 2px;
				border: none;
				outline: none !important;
				margin-left: 10px;
			}

				.table-title .btn i {
					float: left;
					font-size: 21px;
					margin-right: 5px;
				}

				.table-title .btn span {
					float: left;
					margin-top: 2px;
				}

		table.table tr th, table.table tr td {
			border-color: #e9e9e9;
			padding: 12px 15px;
			vertical-align: middle;
		}

			table.table tr th:first-child {
				width: 60px;
			}

			table.table tr th:last-child {
				width: 100px;
			}

		table.table-striped tbody tr:nth-of-type(odd) {
			background-color: #fcfcfc;
		}

		table.table-striped.table-hover tbody tr:hover {
			background: #f5f5f5;
		}

		table.table th i {
			font-size: 13px;
			margin: 0 5px;
			cursor: pointer;
		}

		table.table td:last-child i {
			opacity: 0.9;
			font-size: 22px;
			margin: 0 5px;
		}

		table.table td a {
			font-weight: bold;
			color: #566787;
			display: inline-block;
			text-decoration: none;
			outline: none !important;
		}

			table.table td a:hover {
				color: #2196F3;
			}

			table.table td a.edit {
				color: #FFC107;
			}

			table.table td a.delete {
				color: #F44336;
			}

		table.table td i {
			font-size: 19px;
		}

		table.table .avatar {
			border-radius: 50%;
			vertical-align: middle;
			margin-right: 10px;
		}

		.pagination {
			float: right;
			margin: 0 0 5px;
		}

			.pagination li a {
				border: none;
				font-size: 13px;
				min-width: 30px;
				min-height: 30px;
				color: #999;
				margin: 0 2px;
				line-height: 30px;
				border-radius: 2px !important;
				text-align: center;
				padding: 0 6px;
			}

				.pagination li a:hover {
					color: #666;
				}

			.pagination li.active a, .pagination li.active a.page-link {
				background: #03A9F4;
			}

				.pagination li.active a:hover {
					background: #0397d6;
				}

			.pagination li.disabled i {
				color: #ccc;
			}

			.pagination li i {
				font-size: 16px;
				padding-top: 6px
			}

		.hint-text {
			float: left;
			margin-top: 10px;
			font-size: 13px;
		}
		/* Custom checkbox */
		.custom-checkbox {
			position: relative;
		}

			.custom-checkbox input[type="checkbox"] {
				opacity: 0;
				position: absolute;
				margin: 5px 0 0 3px;
				z-index: 9;
			}

			.custom-checkbox label:before {
				width: 18px;
				height: 18px;
			}

			.custom-checkbox label:before {
				content: '';
				margin-right: 10px;
				display: inline-block;
				vertical-align: text-top;
				background: white;
				border: 1px solid #bbb;
				border-radius: 2px;
				box-sizing: border-box;
				z-index: 2;
			}

			.custom-checkbox input[type="checkbox"]:checked + label:after {
				content: '';
				position: absolute;
				left: 6px;
				top: 3px;
				width: 6px;
				height: 11px;
				border: solid #000;
				border-width: 0 3px 3px 0;
				transform: inherit;
				z-index: 3;
				transform: rotateZ(45deg);
			}

			.custom-checkbox input[type="checkbox"]:checked + label:before {
				border-color: #03A9F4;
				background: #03A9F4;
			}

			.custom-checkbox input[type="checkbox"]:checked + label:after {
				border-color: #fff;
			}

			.custom-checkbox input[type="checkbox"]:disabled + label:before {
				color: #b8b8b8;
				cursor: auto;
				box-shadow: none;
				background: #ddd;
			}
		/* Modal styles */
		.modal .modal-dialog {
			max-width: 400px;
		}

		.modal .modal-header, .modal .modal-body, .modal .modal-footer {
			padding: 20px 30px;
		}

		.modal .modal-content {
			border-radius: 3px;
			font-size: 14px;
		}

		.modal .modal-footer {
			background: #ecf0f1;
			border-radius: 0 0 3px 3px;
		}

		.modal .modal-title {
			display: inline-block;
		}

		.modal .form-control {
			border-radius: 2px;
			box-shadow: none;
			border-color: #dddddd;
		}

		.modal textarea.form-control {
			resize: vertical;
		}

		.modal .btn {
			border-radius: 2px;
			min-width: 100px;
		}

		.modal form label {
			font-weight: normal;
		}
	</style>
	<script>
		$(document).ready(function () {
			// Activate tooltip
			$('[data-toggle="tooltip"]').tooltip();

			// Select/Deselect checkboxes
			var checkbox = $('table tbody input[type="checkbox"]');
			$("#selectAll").click(function () {
				if (this.checked) {
					checkbox.each(function () {
						this.checked = true;
					});
				} else {
					checkbox.each(function () {
						this.checked = false;
					});
				}
			});
			checkbox.click(function () {
				if (!this.checked) {
					$("#selectAll").prop("checked", false);
				}
			});
		});
	</script>
</head>
<body>
	@if (Model != null)
	{
		<div class="container-l">
			<div class="table-responsive">
				<div class="table-wrapper">
					<div class="table-title">
						<div class="row">
							<div class="col-sm-6">
								<h2>Manage <b>Roads</b></h2>
							</div>
							<div class="col-sm-6">

								<a asp-action="Create" class="btn btn-success"><i class="material-icons">&#xE147;</i> <span>Add New Road</span></a>
								
							</div>
						</div>
					</div>
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								
								<th>
									@Html.DisplayNameFor(model => model.Id)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.Origin)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.Distination)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.Distance)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.Classification)
								</th>

								
								<th>
									@Html.DisplayNameFor(model => model.CreatedDate)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.UpdatedDate)
								</th>

							</tr>
						</thead>
						<tbody>
							<tr>

								@foreach (var item in Model)
								{
									<tr>

										<td>
											@Html.DisplayFor(modelItem => item.Id)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Origin)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Distination)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Distance)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Classification)
										</td>

									
										<td>
											@Html.DisplayFor(modelItem => item.CreatedDate)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.UpdatedDate)
										</td>
									
									<td>
										<a class="edit" asp-action="Edit" asp-route-id="@item.Id"><i class="material-icons" title="Edit" style="margin-top=30px">&#xE254;</i></a>
										<a class="delete" asp-action="Delete" asp-route-id="@item.Id"><i class="material-icons" title="Delete" style="margin-top=30px">&#xE872;</i></a>
										<a class="details" asp-action="Details" asp-route-id="@item.Id"><img class="material-icons" src="~/NiceAdmin/assets/img/icons8-info-48.png" style="width:25px;height=20px ;margin-bottom=30px" /></a>

										</td>
									</tr>
								}



							</tr>

						</tbody>
					</table>
					@*<div class="clearfix">
						<div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
						<ul class="pagination">
							<li class="page-item disabled"><a href="#">Previous</a></li>
							<li class="page-item"><a href="#" class="page-link">1</a></li>
							<li class="page-item"><a href="#" class="page-link">2</a></li>
							<li class="page-item active"><a href="#" class="page-link">3</a></li>
							<li class="page-item"><a href="#" class="page-link">4</a></li>
							<li class="page-item"><a href="#" class="page-link">5</a></li>
							<li class="page-item"><a href="#" class="page-link">Next</a></li>
						</ul>
					</div>*@
				</div>
			</div>
		</div>
	}else
	{
		<h1>No Data Available</h1>
	}
	
</body>
</html>