Models/AirCraft.cs
using AirLine.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;

namespace AirLine.Models
{
    public class AirCraft:Entity<int>
    {

        [MaxLength(20)]
        public string Model { get; set; }

        public int Capacity { get; set; }
        public string  Major_Poilot { get; set; }
        public string Assistant_Pilot  { get; set; }
        public string Host1 { get; set; }
        public string Host2 { get; set; }
       
        public AirLine_Company AirLine { get; set; }
     
        public int  AirlineId { get; set; }


        public ICollection<Road_Craft> Craft_Roads { get; set; }


    }
}

Controllers/AirCraftController.cs
using AirLine.Models;
using AirLine.MyDBContext;
using AirLine.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AirLine.Controllers
{
    public class AirCraftController : Controller
    {
        private readonly DBContext _dBContext;
        public AirCraftController(DBContext dBContext)
        {
            _dBContext = dBContext;
        }

        // GET: AirCraftController
        public ActionResult Index()
        {
			var airCrafts = _dBContext.AirCrafts.ToList();

			var AirCrafmodel = new List<AirCraftModel>();
			foreach (var craft in airCrafts)
			{
				var viewModel = new AirCraftModel()
				{
					Id = craft.Id,
					Model = craft.Model,
					Capacity = craft.Capacity,
					Major_Poilot = craft.Major_Poilot,
					Assistant_Pilot = craft.Assistant_Pilot,
					Host1 = craft.Host1,
					Host2 = craft.Host2,
					AirlineId = craft.AirlineId,
					UpdatedDate = craft.UpdatedDate,
                    CreatedDate= craft.CreatedDate,
					IsDeleted = craft.IsDeleted,
					IsVisable = craft.IsVisable,
				};
				AirCrafmodel.Add(viewModel);
			}
			return View(AirCrafmodel);
			
        }

        // GET: AirCraftController/Details/5
        public ActionResult Details(int id)
        {
            var CraftDE = _dBContext.AirCrafts.Where(r => r.Id == id).FirstOrDefault();

            return View(CraftDE);
        }

        // GET: AirCraftController/Create
        public ActionResult Create()
        {
            AirCraftModel AirModel = new AirCraftModel();
            var airline = _dBContext.AirLine_Companies.ToList();
            AirModel.AirLines = airline;
            return View(AirModel);
        }

        // POST: AirCraftController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AirCraftModel airCraftModel)
        {
            try
            {
                AirCraft air = new AirCraft()
                {
                    Id = airCraftModel.Id,
                    Model = airCraftModel.Model,
                    Capacity = airCraftModel.Capacity,
                    Major_Poilot = airCraftModel.Major_Poilot,
                    Assistant_Pilot = airCraftModel.Assistant_Pilot,
                    Host1 = airCraftModel.Host1,
                    Host2 = airCraftModel.Host2,
                    AirlineId= airCraftModel.AirlineId,

					CreatedDate = DateTime.Now,
                    UpdatedDate = DateTime.Now,
                    IsDeleted = false,
                    IsVisable = true,


                };
                air.IsDeleted = false;
                air.IsVisable = true;
                _dBContext.Add(air);
                //_dBContext.AirCrafts.Add(air);
                _dBContext.SaveChanges();

               
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AirCraftController/Edit/5
        public ActionResult Edit(int id)
        {
            AirCraftModel AirModel = new AirCraftModel();
            var airline = _dBContext.AirLine_Companies.ToList();
           
            var CraftE = _dBContext.AirCrafts.Where(r => r.Id == id).FirstOrDefault();
            var viewModel = new AirCraftModel
            {
                Id = CraftE.Id,
                Model = CraftE.Model,
                Capacity = CraftE.Capacity,
                Major_Poilot = CraftE.Major_Poilot,
                Assistant_Pilot = CraftE.Assistant_Pilot,
                Host1 = CraftE.Host1,
                Host2 = CraftE.Host2,
               AirlineId=CraftE.AirlineId,
                IsDeleted = CraftE.IsDeleted,
                IsVisable = CraftE.IsVisable,
                CreatedDate = CraftE.CreatedDate,
                UpdatedDate = CraftE.UpdatedDate,
            };
            viewModel.AirLines = airline;
            return View(viewModel);
        }

        // POST: AirCraftController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AirCraftModel craftModel)
        {
            try
            {
                var originalRoad = _dBContext.AirCrafts.Where(r => r.Id == craftModel.Id).FirstOrDefault();


                originalRoad.Id = craftModel.Id;
                originalRoad.Model = craftModel.Model;
                originalRoad.Capacity = craftModel.Capacity;
                originalRoad.Major_Poilot = craftModel.Major_Poilot;
                originalRoad.Assistant_Pilot = craftModel.Assistant_Pilot;
                originalRoad.Host1 = craftModel.Host1;
                originalRoad.Host2 = craftModel.Host2;
                originalRoad.AirlineId = craftModel.AirlineId;


                originalRoad.IsVisable = craftModel.IsVisable;
                originalRoad.IsDeleted = craftModel.IsDeleted;
                originalRoad.CreatedDate = craftModel.CreatedDate;
                originalRoad.UpdatedDate = craftModel.UpdatedDate;



                _dBContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AirCraftController/Delete/5
        public ActionResult Delete(int id)
        {
            var CraftD = _dBContext.AirCrafts.Where(r => r.Id == id).FirstOrDefault();
            return View(CraftD);
        }

        // POST: AirCraftController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(AirCraft airCraft)
        {
            try
            {

                var CraftDelete = _dBContext.AirCrafts.Where(r => r.Id == airCraft.Id).FirstOrDefault();
                _dBContext.AirCrafts.Remove(CraftDelete);

                _dBContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/AirCraft/Create.cshtml
@model AirLine.ViewModel.AirCraftModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create AirCraft</h1>


<hr />
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Create Road</h5>

        <!-- No Labels Form -->
        <form class="row g-3" asp-action="Create" asp-controller="AirCraft">
            <div class="col-md-6">
                <label>ID</label>
                <input asp-for="Id" class="form-control" placeholder="ID">
            </div>
            <div class="col-md-6">
                <label>Model</label>
                <input asp-for="Model" class="form-control" placeholder="Model">
            </div>
            <div class="col-md-6">
                <label>Capacity</label>
                <input asp-for="Capacity" class="form-control" placeholder="Capacity">
            </div>
            <div class="col-md-6">
                <label>Major_Poilot</label>
                <input asp-for="Major_Poilot" class="form-control" placeholder="Major_Poilot">
            </div>
     
            <div class="col-md-6">
                <label>Assistant_Pilot</label>
                <input asp-for="Assistant_Pilot" class="form-control" placeholder="Assistant_Pilot">
            </div>
            <div class="col-md-6">
                <label>Host1</label>
                <input asp-for="Host1" class="form-control" placeholder="Host1">
            </div>
            <div class="col-md-6">
                <label>Host2</label>
                <input asp-for="Host2" class="form-control" placeholder="Host2">
            </div>


            <div class="col-md-4">
                <label>AirLine Name</label>
                <select asp-for="AirlineId"  class="form-control" asp-items="@(new SelectList(Model.AirLines,"Id" ,"Name" ))"></select>
                   
            </div>

            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form><!-- End No Labels Form -->

    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AirCraft/Delete.cshtml
@model AirLine.Models.AirCraft

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete AirCraft</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Major_Poilot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Major_Poilot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assistant_Pilot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assistant_Pilot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Host1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Host1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Host2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Host2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirlineId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirlineId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVisable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVisable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-primary">Back to List</a>
    </form>
</div>

Views/AirCraft/Details.cshtml
@model AirLine.Models.AirCraft

@{
    ViewData["Title"] = "Details";
}

<h1>Details AirCraft</h1>

<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Major_Poilot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Major_Poilot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assistant_Pilot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assistant_Pilot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Host1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Host1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Host2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Host2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirlineId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirlineId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVisable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVisable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/AirCraft/Edit.cshtml
@model AirLine.ViewModel.AirCraftModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit AirCraft</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Major_Poilot" class="control-label"></label>
                <input asp-for="Major_Poilot" class="form-control" />
                <span asp-validation-for="Major_Poilot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Assistant_Pilot" class="control-label"></label>
                <input asp-for="Assistant_Pilot" class="form-control" />
                <span asp-validation-for="Assistant_Pilot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Host1" class="control-label"></label>
                <input asp-for="Host1" class="form-control" />
                <span asp-validation-for="Host1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Host2" class="control-label"></label>
                <input asp-for="Host2" class="form-control" />
                <span asp-validation-for="Host2" class="text-danger"></span>
            </div>
            <div class="form-group">
               
                    <label>AirLine Name</label>
                    <select asp-for="AirlineId" class="form-control" asp-items="@(new SelectList(Model.AirLines,"Id" ,"Name" ))"></select>

            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVisable" /> @Html.DisplayNameFor(model => model.IsVisable)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}